# Clinical Metabolomics Oracle Web Search Agent - Default Configuration
# This file contains all available configuration options with their default values.
# Copy this file and modify the values as needed for your use case.

# The query to search for (can be overridden via command line)
query: ""

# Search Configuration
search:
  # Search provider(s) to use: "all", "selenium", "playwright", "brave", "google_cse"
  # Use "all" to use all available providers
  provider: "all"
  
  # Maximum number of search results to collect
  max_results: 10
  
  # Maximum number of URLs to extract content from
  max_urls: 3
  
  # Timeout for search operations in seconds
  timeout: 30
  
  # Enable caching of search results
  cache: true
  
  # Force refresh of cached results
  force_refresh: false

# LLM Configuration
llm:
  # LLM API provider to use: "openai", "anthropic", "openrouter", "local"
  provider: "openrouter"
  
  # LLM model to use (depends on provider)
  model: "gpt-4o-mini"
  
  # Temperature parameter for LLM (0.0 = deterministic, 2.0 = very random)
  temperature: 0.1
  
  # Maximum tokens for LLM response
  max_tokens: 1024
  
  # Enable answer quality evaluation
  evaluation: true

# Output Configuration
output:
  # Directory to save results
  directory: "./output"
  
  # Base name for output files
  file: "answer_result"
  
  # Absolute path for output file (overrides directory + file if specified)
  path: null
  
  # Project name for organizing results
  project_name: "default_project"

# Advanced Configuration
advanced:
  # Proxy URL for web requests (e.g., "http://proxy.example.com:8080")
  proxy: null
  
  # Custom user agent for web requests
  user_agent: null
  
  # Number of retries for failed operations
  retry_count: 3
  
  # Extract and include images in results
  extract_images: false
  
  # Save raw HTML of extracted pages
  save_html: false
  
  # Enable debug mode
  debug: false

# API Keys (set these via environment variables for security)
# BRAVE_API_KEY: "your_brave_api_key_here"
# GOOGLE_API_KEY: "your_google_api_key_here"
# OPENAI_API_KEY: "your_openai_api_key_here"
# ANTHROPIC_API_KEY: "your_anthropic_api_key_here"
# OPENROUTER_API_KEY: "your_openrouter_api_key_here"
# GOOGLE_CSE_ID: "your_google_cse_id_here"

# Example configurations for different use cases:

# Example 1: Fast search with minimal results
# search:
#   provider: "brave"
#   max_results: 5
#   max_urls: 2
#   timeout: 15
# llm:
#   provider: "openai"
#   model: "gpt-3.5-turbo"
#   temperature: 0.0
#   max_tokens: 512

# Example 2: Comprehensive search with detailed analysis
# search:
#   provider: "all"
#   max_results: 20
#   max_urls: 5
#   timeout: 60
# llm:
#   provider: "openai"
#   model: "gpt-4"
#   temperature: 0.1
#   max_tokens: 2048
# advanced:
#   extract_images: true
#   save_html: true

# Example 3: Research-focused configuration
# search:
#   provider: "google_cse"
#   max_results: 15
#   max_urls: 3
# llm:
#   provider: "anthropic"
#   model: "claude-3-sonnet"
#   temperature: 0.0
#   max_tokens: 4096
#   evaluation: true

# Example 4: Debug configuration
# search:
#   provider: "selenium"
#   max_results: 3
#   max_urls: 1
# advanced:
#   debug: true
#   retry_count: 1
# llm:
#   provider: "openai"
#   model: "gpt-3.5-turbo"
#   temperature: 0.0